package com;



/**
 * Emp generated by MyEclipse - Hibernate Tools
 */

public class Emp  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String empname;


    // Constructors

    /** default constructor */
    public Emp() {
    }

	/** minimal constructor */
    public Emp(Integer id) {
        this.id = id;
    }
    
    /** full constructor */
    public Emp(Integer id, String empname) {
        this.id = id;
        this.empname = empname;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getEmpname() {
        return this.empname;
    }
    
    public void setEmpname(String empname) {
        this.empname = empname;
    }
   








}