package com.ram.model;
// Generated Apr 4, 2020 2:17:27 AM by Hibernate Tools 5.2.10.Final

/**
 * AddressManyToOne generated by hbm2java
 */
public class AddressManyToOne implements java.io.Serializable {

	private int aid;
	private String city;
	private String dist;
	private String state;

	public AddressManyToOne() {
	}

	public AddressManyToOne(int aid, String city, String dist, String state) {
		this.aid = aid;
		this.city = city;
		this.dist = dist;
		this.state = state;
	}

	public int getAid() {
		return this.aid;
	}

	public void setAid(int aid) {
		this.aid = aid;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getDist() {
		return this.dist;
	}

	public void setDist(String dist) {
		this.dist = dist;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Override
	public String toString() {
		return "AddressManyToOne [aid=" + aid + ", city=" + city + ", dist=" + dist + ", state=" + state + "]";
	}
	
	

}
