package com.ram.model;
// Generated Apr 4, 2020 2:17:27 AM by Hibernate Tools 5.2.10.Final

/**
 * PersionManyToOne generated by hbm2java
 */
public class PersionManyToOne implements java.io.Serializable {

	private int pid;
	private String name;
	private int age;
	private AddressManyToOne address;

	public PersionManyToOne() {
	}

	public PersionManyToOne(int pid, String name, int age, AddressManyToOne address) {
		super();
		this.pid = pid;
		this.name = name;
		this.age = age;
		this.address = address;
	}

	public int getPid() {
		return pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getAge() {
		return age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public AddressManyToOne getAddress() {
		return address;
	}

	public void setAddress(AddressManyToOne address) {
		this.address = address;
	}

	@Override
	public String toString() {
		return "PersionManyToOne [pid=" + pid + ", name=" + name + ", age=" + age + ", address=" + address + "]";
	}

	

}
