package com.jbk.crud;



/**
 * City generated by MyEclipse - Hibernate Tools
 */

public class City  implements java.io.Serializable {


    // Fields    

     private Integer sid;
     private Student student;
     private String cid;
     private String cname;


    // Constructors

    /** default constructor */
    public City() {
    }

    
    /** full constructor */
    public City(Integer sid, Student student, String cid, String cname) {
        this.sid = sid;
        this.student = student;
        this.cid = cid;
        this.cname = cname;
    }

   
    // Property accessors

    public Integer getSid() {
        return this.sid;
    }
    
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

    public String getCid() {
        return this.cid;
    }
    
    public void setCid(String cid) {
        this.cid = cid;
    }

    public String getCname() {
        return this.cname;
    }
    
    public void setCname(String cname) {
        this.cname = cname;
    }
   








}