package com.jbk.crud;

import java.util.HashSet;
import java.util.Set;


/**
 * Student generated by MyEclipse - Hibernate Tools
 */

public class Student  implements java.io.Serializable {


    // Fields    

   

	private Integer sid;
     private String sname;
     private Set cities = new HashSet(0);


    // Constructors

    /** default constructor */
    public Student() {
    }

	/** minimal constructor */
    public Student(Integer sid, String sname) {
        this.sid = sid;
        this.sname = sname;
    }
    
    /** full constructor */
    public Student(Integer sid, String sname, Set cities) {
        this.sid = sid;
        this.sname = sname;
        this.cities = cities;
    }

   
    

	public Integer getSid() {
        return this.sid;
    }
    
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    public String getSname() {
        return this.sname;
    }
    
    public void setSname(String sname) {
        this.sname = sname;
    }

    public Set getCities() {
        return this.cities;
    }
    
    public void setCities(Set cities) {
        this.cities = cities;
    }
   








}